name       : perl-pod-coverage
version    : 0.23
release    : 2
source     :
    - https://cpan.metacpan.org/authors/id/R/RC/RCLAMP/Pod-Coverage-0.23.tar.gz : 30b7a0b0c942f44a7552c0d34e9b1f2e0ba0b67955c61e3b1589ec369074b107
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Checks if the documentation of a module is comprehensive
description: "Checks if the documentation of a module is comprehensive \n"
builddeps  :
    - perl-devel-symdump
    - perl-test-pod
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
